# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_removePages.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RemovePagesWindow(object):
    def setupUi(self, RemovePagesWindow):
        RemovePagesWindow.setObjectName("RemovePagesWindow")
        RemovePagesWindow.resize(800, 315)
        self.centralwidget = QtWidgets.QWidget(RemovePagesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 80, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(220, 80, 261, 81))
        self.plainTextEdit.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 60, 81, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 210, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 210, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        RemovePagesWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RemovePagesWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        RemovePagesWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RemovePagesWindow)
        self.statusbar.setObjectName("statusbar")
        RemovePagesWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RemovePagesWindow)
        QtCore.QMetaObject.connectSlotsByName(RemovePagesWindow)

    def retranslateUi(self, RemovePagesWindow):
        _translate = QtCore.QCoreApplication.translate
        RemovePagesWindow.setWindowTitle(_translate("RemovePagesWindow", "MainWindow"))
        self.plainTextEdit.setPlainText(_translate("RemovePagesWindow", "1            -> remove page 1\n"
"1-5         -> remove pages 1 to 5\n"
"1,6         -> remove page 1 and 6\n"
"1,3-5,8  -> remove page 1 and 2 and 3 to 5 and 8"))
        self.label.setText(_translate("RemovePagesWindow", "Allowed format"))
        self.pushButton.setText(_translate("RemovePagesWindow", "remove"))
        self.pushButton_2.setText(_translate("RemovePagesWindow", "Close"))
